# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Resep Bango App iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~>4.5.1'
  pod 'SwiftyJSON', '~>4.0.0'

  # Pods for Resep Bango App iOS

  target 'Resep Bango App iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Resep Bango App iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
